-- CREATE SEQUENCE hibernate_sequence START 1 INCREMENT 1;
-- CREATE SEQUENCE department_depid_seq START 4 INCREMENT 10;
-- CREATE SEQUENCE position_posid_seq START 6 INCREMENT 10;
-- CREATE SEQUENCE employee_empid_seq START 7 INCREMENT 10;

CREATE TABLE IF NOT EXISTS department
(
    depid           INT         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR(25) NOT NULL UNIQUE,
    CONSTRAINT departments_pk PRIMARY KEY (depid)
);

CREATE TABLE IF NOT EXISTS position
(
    posid         INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    depid         INT          NOT NULL,
    position_name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_position_depid FOREIGN KEY (depid) REFERENCES department (depid) ON DELETE CASCADE,
    CONSTRAINT positions_pk PRIMARY KEY (posid)
);

CREATE TABLE IF NOT EXISTS employee
(
    empid         INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    full_name     VARCHAR(255) NOT NULL,
    date_of_birth TIMESTAMP WITHOUT TIME ZONE,
    salary        INTEGER      NOT NULL,
    CONSTRAINT employees_pk PRIMARY KEY (empid)
);

CREATE TABLE IF NOT EXISTS positions_employees
(
    posid INT NOT NULL,
    empid INT NOT NULL,
    CONSTRAINT fk_positions_employees_posid FOREIGN KEY (posid) REFERENCES position (posid) ON DELETE CASCADE,
    CONSTRAINT fk_positions_employees_empid FOREIGN KEY (empid) REFERENCES employee (empid) ON DELETE CASCADE,
    PRIMARY KEY (posid, empid)
);